# Generated by Django 3.0.6 on 2020-05-14 11:59

from django.db import migrations
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', forum.models.MyUserManager()),
            ],
        ),
    ]
