# Generated by Django 3.0.7 on 2020-06-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200608_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedAnswers',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forum.Question')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.Answer')),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerApply',
        ),
    ]
