# Generated by Django 3.0.7 on 2020-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200611_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttoanswer',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='commenttoquestion',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
