# Generated by Django 3.0.7 on 2020-06-17 13:44

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200611_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=forum.models.User.upload_avatar_filename),
        ),
    ]
