# Generated by Django 3.0.6 on 2020-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20200519_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/uploads/avatar/default.png', upload_to='uploads/avatar/'),
        ),
    ]
