# Generated by Django 3.0.6 on 2020-05-23 17:39

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20200519_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to=forum.models.upload_avatar_filename),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('author', 'like')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('author', 'like')},
        ),
    ]
