# Generated by Django 3.0.6 on 2020-05-23 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20200523_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlike',
            name='id',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='id',
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='like',
            field=models.BooleanField(db_index=True, default=True, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='like',
            field=models.BooleanField(db_index=True, default=True, verbose_name='like'),
        ),
    ]
